export {
  ANY,
  CAPABILITY_ASSET_CLASSES,
  CAPABILITY_CONTENT_KINDS,
  CAPABILITY_KEYS,
  CAPABILITY_REASON_CODES,
  CAPABILITY_SOURCES,
  CAPABILITY_STATES,
  LIMITATION_CODES,
  isCapabilityContentKind,
  isCapabilityKey,
  isCapabilitySource,
  type CapabilityAssetClass,
  type CapabilityContentKind,
  type CapabilityKey,
  type CapabilityReasonCode,
  type CapabilitySource,
  type CapabilityState,
  type Limitation,
  type ScopeKind,
  type ScopeSource,
} from "./domain/vocabulary";
export { CATALOG_IDS, PLATFORM_CATALOG, SIMULATOR_CATALOG, lookupCatalog, profileScopes, type CapabilityCatalog, type CatalogEntry, type CatalogId } from "./domain/catalog";
export {
  AVAILABILITY_REASONS,
  AVAILABILITY_STATES,
  RECOVERY_HINTS,
  effectiveAvailability,
  evaluateProfile,
  factsObservedAt,
  resolveEntry,
  type AccountFacts,
  type AvailabilityReason,
  type AvailabilityState,
  type CapabilityAvailability,
  type CapabilityObservation,
  type CapabilityProfile,
  type EvaluationInput,
  type FactsInput,
  type FactsUnavailable,
  type ProfileEntry,
  type RecoveryHint,
} from "./domain/profile";
export {
  compareFreshness,
  type CapabilityProfileStore,
  type Freshness,
  type FreshnessVerdict,
  type CapabilityReadStore,
  type ProfileWrite,
  type ProfileWriteOutcome,
  type StoredProfileHeader,
} from "./application/ports";
export {
  CapabilityCatalogError,
  SIMULATOR_CATALOG_ENVIRONMENTS,
  capabilityAvailability,
  evaluateAndStore,
  factsFromDescription,
  inputDigest,
  observationFromError,
  selectCatalog,
  type EvaluateAndStoreInput,
} from "./application/evaluation";
