/**
 * Provider adapter contract (TA §15): provider-neutral ports (read, authorization), normalized DTOs, errors,
 * pagination, rate-budget signals and webhook hints. Pure: depends only on the shared kernel; no SDK, HTTP or I/O.
 *
 * The MUTATION port is deliberately NOT re-exported here: it lives in `./mutation-port`, which only the
 * executor's composition may import (TA §6.3 rule 3; enforced by dependency rules).
 */
export const PROVIDER_CONTRACT_VERSION = 1;

export {
  PROVIDER_NAMES,
  PROVIDER_OBJECT_KINDS,
  isoInstant,
  parseIsoInstant,
  parseProviderObjectId,
  providerObjectKey,
  providerObjectRef,
  rawReference,
  sameProviderObject,
  type IsoInstant,
  type ProviderName,
  type ProviderObjectId,
  type ProviderObjectKind,
  type ProviderObjectRef,
  type ProviderTimestamps,
  type RawReference,
} from "./identity";
export { SecretValue, providerCredential, type ProviderCredential } from "./credential";
export {
  BUDGET_NOT_REPORTED,
  parsePageCursor,
  type Page,
  type PageCursor,
  type PageNext,
  type ProviderResult,
  type RateBudgetSignal,
  type TimeWindow,
} from "./pagination";
export {
  ASSET_CLASSES,
  AUTHOR_ROLES,
  CONTENT_AVAILABILITY,
  CONTENT_KINDS,
  CONTENT_SOURCES,
  INTERACTION_AVAILABILITY,
  INTERACTION_KINDS,
  INTERACTION_VISIBILITY,
  OBSERVATION_BASES,
  PAID_STATUSES,
  PRESENCE_STATES,
  type AccountDescriptionDto,
  type AdDto,
  type AdGroupDto,
  type AssetClass,
  type AuthorDto,
  type AuthorRole,
  type CampaignDto,
  type ContentAvailability,
  type ContentDto,
  type ContentKind,
  type ContentSource,
  type CredentialRefreshResult,
  type InteractionAvailability,
  type InteractionDto,
  type InteractionKind,
  type InteractionVisibility,
  type ObservationBasis,
  type PaidContextItem,
  type PaidStatus,
  type PresenceState,
  type ProviderAccess,
  type SocialAssetDto,
  type StateObservationDto,
  type StateTarget,
  type SubscriptionResultDto,
} from "./dto";
export {
  AUTHORIZATION_OPERATIONS,
  CREDENTIAL_INVALID_REASONS,
  MUTATION_OPERATIONS,
  NOT_ELIGIBLE_REASONS,
  PERMANENT_REJECTION_CODES,
  PERMISSION_CAPABILITIES,
  PROVIDER_ERROR_KINDS,
  READ_OPERATIONS,
  TRANSIENT_REASONS,
  CredentialInvalidError,
  OutcomeUnknownError,
  PermanentRejectedError,
  PermissionMissingError,
  ProviderError,
  RateLimitedError,
  TargetNotEligibleError,
  TargetNotFoundError,
  TransientError,
  isDefiniteFailure,
  isProviderError,
  type AuthorizationOperation,
  type CredentialInvalidReason,
  type MutationOperation,
  type NotEligibleReason,
  type PermanentRejectionCode,
  type PermissionCapability,
  type ProviderErrorKind,
  type ProviderOperation,
  type ProviderRetry,
  type ReadOperation,
  type SerializedProviderError,
  type TransientReason,
} from "./errors";
export {
  WEBHOOK_HINT_CHANGES,
  WEBHOOK_REJECTION_REASONS,
  WebhookRejectedError,
  type WebhookEventHint,
  type WebhookHintChange,
  type WebhookParseResult,
  type WebhookRejectionReason,
  type WebhookRequest,
} from "./webhooks";
export type { InteractionScope, ProviderReadPort } from "./read-port";
export {
  CALLBACK_DENIAL_REASONS,
  CALLBACK_MALFORMED_REASONS,
  PKCE_SUPPORT,
  isGrantedScope,
  isPkceVerifierShape,
  parseAuthorizationCode,
  parseOAuthState,
  parsePkceChallenge,
  parsePkceVerifier,
  parseRedirectUri,
  type AuthorizationRequest,
  type AuthorizationRequestInput,
  type CallbackDenialReason,
  type CallbackMalformedReason,
  type CallbackOutcome,
  type CallbackQuery,
  type CodeExchangeInput,
  type CodeExchangeResult,
  type OAuthState,
  type PkceChallenge,
  type PkceChallengeValue,
  type PkceSupport,
  type ProviderAuthorizationPort,
  type RedirectUri,
} from "./authorization-port";
